#!/bin/bash
cwd=$(pwd)
parent_dir=$(dirname "$cwd")
for file in "$cwd"/*.html; do
    
    filename=$(basename "$file")
    if [[ ! -e "$parent_dir/$filename" || "$file" -nt "$parent_dir/$filename" ]]; then
        cp "$file" "$parent_dir"
    fi
done

