#!/usr/bin/env bash
# This script is modifying hosts.

# Copie le fichier hosts dans le répertoire personnel de l'utilisateur
cp /etc/hosts ~/hosts.new

# Modifie le fichier hosts.new en remplaçant les adresses IP spécifiées
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

# Copie le fichier modifié dans le répertoire système /etc/hosts
cp -f ~/hosts.new /etc/hosts
