#!/usr/bin/env bash
# Sauvegardez le fichier /etc/hosts d'origine
sudo cp /etc/hosts /etc/hosts.bak

# Remplacez localhost par 127.0.0.2
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts

# Changez Facebook.com en 8.8.8.8
sudo sed -i 's/facebook.com/8.8.8.8 facebook.com/' /etc/hosts

# Afficher un message
echo "Host configurations updated."

# Afficher le fichier /etc/hosts mis à jour
echo "Updated /etc/hosts file:"
cat /etc/hosts
