#!/usr/bin/env bash
# Sauvegardez le fichier /etc/hosts d'origine
sudo cp /etc/hosts /etc/hosts.bak
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/facebook.com/8.8.8.8 facebook.com/' /etc/hosts
echo "Host configurations updated."
echo "Updated /etc/hosts file:"
cat /etc/hosts
